# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BooksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBook = channel.unary_unary(
                '/books.Books/getBook',
                request_serializer=books__pb2.getBookRequest.SerializeToString,
                response_deserializer=books__pb2.getBookResponse.FromString,
                )
        self.setBook = channel.unary_unary(
                '/books.Books/setBook',
                request_serializer=books__pb2.createBookRequest.SerializeToString,
                response_deserializer=books__pb2.createBookResponse.FromString,
                )


class BooksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBook': grpc.unary_unary_rpc_method_handler(
                    servicer.getBook,
                    request_deserializer=books__pb2.getBookRequest.FromString,
                    response_serializer=books__pb2.getBookResponse.SerializeToString,
            ),
            'setBook': grpc.unary_unary_rpc_method_handler(
                    servicer.setBook,
                    request_deserializer=books__pb2.createBookRequest.FromString,
                    response_serializer=books__pb2.createBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.Books', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Books(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.Books/getBook',
            books__pb2.getBookRequest.SerializeToString,
            books__pb2.getBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.Books/setBook',
            books__pb2.createBookRequest.SerializeToString,
            books__pb2.createBookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
